#!/usr/bin/env python3

# Copyright (C) 2026 Julian Pawlowski
# All rights reserved. BSD-2-Clause, see LICENSE at the repository root.

"""Refresh or verify the generated host-independent test evidence in the audit report."""

import argparse
import pathlib
import re
import subprocess
import sys


ROOT = pathlib.Path(__file__).resolve().parent.parent
REPORT = ROOT / "docs" / "reference" / "audit-report.md"
START = "<!-- BEGIN GENERATED: host-independent-test-evidence -->"
END = "<!-- END GENERATED: host-independent-test-evidence -->"
STAGES = (
    ("syntax", "Syntax", "== syntax =="),
    ("behaviour", "Behaviour", "== behaviour =="),
    ("convention", "Commit/release convention", "== what a commit message may be =="),
    ("package", "Package/archive/supply chain", "== the package that gets built =="),
)


def stage_output(output, heading):
    """Return one runner section, or None when fail-fast stopped before it."""
    start = output.find(heading)
    if start < 0:
        return None
    following = [output.find(other, start + len(heading)) for _, _, other in STAGES]
    following = [position for position in following if position >= 0]
    end = min(following) if following else len(output)
    return output[start:end]


def results(output):
    """Turn the stable human-readable summaries from tests/run.sh into report rows."""
    parsed = []
    for key, label, heading in STAGES:
        section = stage_output(output, heading)
        if section is None:
            parsed.append((label, "not run", "the suite stopped at an earlier stage"))
            continue
        if key == "syntax":
            if "all files parse" in section:
                parsed.append((label, "passed", "all files parse"))
            else:
                parsed.append((label, "failed", "syntax stage did not complete"))
            continue
        summary = re.search(r"(?m)^(\d+) checks passed(?:, none failed\.|, (\d+) FAILED:)", section)
        if summary is None:
            parsed.append((label, "failed", "test stage did not produce its summary"))
            continue
        passed = int(summary.group(1))
        failed = int(summary.group(2) or 0)
        if failed:
            parsed.append((label, "failed", f"{passed} passed; {failed} failed"))
        else:
            parsed.append((label, "passed", f"{passed} checks passed"))
    return parsed


def generated_block(rows, returncode):
    complete = returncode == 0 and all(status == "passed" for _, status, _ in rows)
    overall = "PASSED" if complete else "FAILED"
    lines = [
        START,
        "The following snapshot is generated by `python3 tests/update-audit-report.py --update`",
        "from the canonical `./tests/run.sh` command. Do not edit the table manually.",
        "",
        f"Overall host-independent result: **{overall}**",
        "",
        "| Stage | Result | Evidence |",
        "|---|---:|---|",
    ]
    for label, status, evidence in rows:
        lines.append(f"| {label} | **{status}** | {evidence} |")
    lines.extend([END, ""])
    return "\n".join(lines)


def replace_generated(report, block):
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END) + r"\n?", re.DOTALL)
    if pattern.search(report) is None:
        raise ValueError("audit report has no generated host-independent evidence markers")
    return pattern.sub(block, report, count=1)


def arguments():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--update", action="store_true", help="replace the generated report snapshot")
    mode.add_argument("--check", action="store_true", help="fail when the generated snapshot is stale")
    parser.add_argument("--quiet", action="store_true", help="do not repeat the underlying test output")
    return parser.parse_args()


def main():
    args = arguments()
    run = subprocess.run(
        [str(ROOT / "tests" / "run.sh")],
        cwd=ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=False,
    )
    if not args.quiet:
        sys.stdout.write(run.stdout)

    report = REPORT.read_text(encoding="utf-8")
    block = generated_block(results(run.stdout), run.returncode)
    refreshed = replace_generated(report, block)

    stale = refreshed != report
    if args.update:
        if stale:
            REPORT.write_text(refreshed, encoding="utf-8")
            print(f"updated {REPORT.relative_to(ROOT)}")
        else:
            print(f"already current: {REPORT.relative_to(ROOT)}")
    elif stale:
        print(
            "audit report test evidence is stale; run "
            "python3 tests/update-audit-report.py --update",
            file=sys.stderr,
        )

    if run.returncode != 0:
        print("host-independent suite failed; the report records that result", file=sys.stderr)
    return 1 if run.returncode != 0 or (args.check and stale) else 0


if __name__ == "__main__":
    sys.exit(main())
